# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "_smk_/jessie64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "../puppet-files/manifests"
    puppet.module_path = "../puppet-files/modules"
  end
end
