forge "https://forge.puppet.com"

mod "camptocamp-openldap", "1.14.0"
mod "puppet-mcollective", "2.2.0"
mod "puppetlabs-rabbitmq",
  :git => "git@github.com:puppetlabs/puppetlabs-rabbitmq.git",
  :ref => "bc10e468cf2c96fd901362a241f1cfe84375dfd5"
